# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 191, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboardButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dashboardButton.setObjectName("dashboardButton")
        self.verticalLayout.addWidget(self.dashboardButton)
        self.serverButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.serverButton.setObjectName("serverButton")
        self.verticalLayout.addWidget(self.serverButton)
        self.serverListView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.serverListView.setStyleSheet("")
        self.serverListView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.serverListView.setObjectName("serverListView")
        self.verticalLayout.addWidget(self.serverListView)
        self.networkButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.networkButton.setObjectName("networkButton")
        self.verticalLayout.addWidget(self.networkButton)
        self.networkListView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.networkListView.setObjectName("networkListView")
        self.verticalLayout.addWidget(self.networkListView)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 80, 1024, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(210, 100, 811, 651))
        self.stackedWidget.setStyleSheet("QStackedWidget {\n"
"    border: 1px solid lightgray;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.dashboard.setFont(font)
        self.dashboard.setObjectName("dashboard")
        self.label_3 = QtWidgets.QLabel(self.dashboard)
        self.label_3.setGeometry(QtCore.QRect(320, 210, 201, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.dashboard)
        self.serverSummary = QtWidgets.QWidget()
        self.serverSummary.setObjectName("serverSummary")
        self.label_4 = QtWidgets.QLabel(self.serverSummary)
        self.label_4.setGeometry(QtCore.QRect(260, 210, 341, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.serverSummary)
        self.kerp = QtWidgets.QWidget()
        self.kerp.setObjectName("kerp")
        self.label = QtWidgets.QLabel(self.kerp)
        self.label.setGeometry(QtCore.QRect(330, 220, 131, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.kerp)
        self.kerpdb = QtWidgets.QWidget()
        self.kerpdb.setObjectName("kerpdb")
        self.label_2 = QtWidgets.QLabel(self.kerpdb)
        self.label_2.setGeometry(QtCore.QRect(330, 250, 131, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.kerpdb)
        self.networkSummary = QtWidgets.QWidget()
        self.networkSummary.setObjectName("networkSummary")
        self.label_5 = QtWidgets.QLabel(self.networkSummary)
        self.label_5.setGeometry(QtCore.QRect(230, 200, 361, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.networkSummary)
        self.HeadUTM = QtWidgets.QWidget()
        self.HeadUTM.setObjectName("HeadUTM")
        self.label_6 = QtWidgets.QLabel(self.HeadUTM)
        self.label_6.setGeometry(QtCore.QRect(290, 240, 361, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.HeadUTM)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AP시스템 모니터링"))
        self.dashboardButton.setText(_translate("Form", "대시보드"))
        self.serverButton.setText(_translate("Form", "서     버"))
        self.networkButton.setText(_translate("Form", "네트워크"))
        self.label_3.setText(_translate("Form", "Dashboard"))
        self.label_4.setText(_translate("Form", "Server Summary"))
        self.label.setText(_translate("Form", "kerp"))
        self.label_2.setText(_translate("Form", "kerpdb"))
        self.label_5.setText(_translate("Form", "Network Summary"))
        self.label_6.setText(_translate("Form", "AP 본사 UTM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

